---
site:
  title: LiteMaaS — AI Model Virtual Key Usage
  url: https://github.com/rhpds/litemaas-virt-key-usage-showroom
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-summit-2025/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui

asciidoc:
  attributes:
    source-highlighter: highlightjs

antora:
  extensions:
    - '@sntke/antora-mermaid-extension'

output:
  dir: ./www
